import { defineBioToolSpec, registryFromTools, type BioToolSpec } from "../core/tool-spec.js";

const jsonObject = { type: "object" } as const;
const stringParam = (description: string) => ({ type: "string", description });

export const bioAgentToolSpecs: BioToolSpec[] = [
  defineBioToolSpec({
    name: "bio.describe-model",
    version: "0.1.0",
    title: "Describe bio agent model",
    description: "Expose the domain model, SQL contracts, ontology/KG shape, and substrate assumptions so the agent can reason about its own abstractions.",
    determinism: "deterministic",
    inputs: [],
    outputs: [{ name: "model", kind: "fact_bundle", formats: ["json"] }],
    surfaces: [{ substrate: "pi", adapter: "pi-coding-agent" }],
    effects: ["read", "prompt"],
    safety: { localFirst: true, factsMustBeToolDerived: true, networkPolicy: "forbidden" },
  }),
  defineBioToolSpec({
    name: "bio.list-tools",
    version: "0.1.0",
    title: "List bio tool specs",
    description: "Return a compact index of provider-agnostic BioToolSpec contracts available to the current agent.",
    determinism: "deterministic",
    inputs: [{ name: "query", kind: "question", required: false }],
    outputs: [{ name: "tool_index", kind: "tool", formats: ["json"] }],
    parameters: [{ name: "query", schema: stringParam("Optional search text"), required: false }],
    surfaces: [{ substrate: "pi", adapter: "pi-coding-agent" }],
    effects: ["read"],
    safety: { localFirst: true, networkPolicy: "forbidden" },
  }),
  defineBioToolSpec({
    name: "bio.list-duckdb-extensions",
    version: "0.1.0",
    title: "List relevant DuckDB extensions",
    description: "Expose extension-backed data substrates without binding the core to a particular runtime or provider.",
    determinism: "deterministic",
    inputs: [{ name: "query", kind: "question", required: false }],
    outputs: [{ name: "extensions", kind: "source", formats: ["json"] }],
    parameters: [{ name: "query", schema: stringParam("Optional search text"), required: false }],
    surfaces: [{ substrate: "pi", adapter: "pi-coding-agent" }],
    effects: ["read"],
    safety: { localFirst: true, networkPolicy: "forbidden" },
  }),
  defineBioToolSpec({
    name: "bio.validate-select",
    version: "0.1.0",
    title: "Validate read-only SQL",
    description: "Check that a graph, ontology, or substrate query is a single read-only SELECT/WITH statement before an execution adapter runs it.",
    determinism: "deterministic",
    inputs: [{ name: "sql", kind: "question", required: true }],
    outputs: [{ name: "validated_sql", kind: "table", formats: ["json"] }],
    parameters: [{ name: "sql", schema: stringParam("Single SELECT or WITH...SELECT statement"), required: true }],
    surfaces: [{ substrate: "duckdb.sql", constraints: { readOnly: true, singleStatement: true, scopedContext: true } }, { substrate: "pi", adapter: "pi-coding-agent" }],
    effects: ["read"],
    safety: { localFirst: true, networkPolicy: "forbidden" },
  }),
  defineBioToolSpec({
    name: "bio.create-skill",
    version: "0.1.0",
    title: "Create project-local skill",
    description: "Persist a reusable workflow as a project-local skill only after the primitive substrate and study notes have stabilized.",
    determinism: "judgment",
    inputs: [{ name: "workflow", kind: "fact_bundle", required: true }],
    outputs: [{ name: "skill", kind: "tool", formats: ["markdown"] }],
    inputSchema: jsonObject,
    surfaces: [{ substrate: "pi", adapter: "pi-coding-agent", constraints: { scopedContext: true } }],
    effects: ["write", "persist", "prompt"],
    safety: { localFirst: true, networkPolicy: "forbidden" },
  }),
  defineBioToolSpec({
    name: "bio.study-notes",
    version: "0.1.0",
    title: "Study-note memory",
    description: "Persist and retrieve corpus maps, cheatsheets, concept maps, probes, failures, and volatile expertise notes as indexed memory instead of premature skill sprawl.",
    determinism: "hybrid",
    inputs: [{ name: "study_note", kind: "study_note", required: false }],
    outputs: [{ name: "study_note_index", kind: "memory", formats: ["json"] }],
    surfaces: [{ substrate: "memory", adapter: "filesystem-json" }, { substrate: "pi", adapter: "pi-coding-agent" }],
    effects: ["read", "write", "index", "persist"],
    safety: { localFirst: true, networkPolicy: "forbidden" },
  }),
];

export const defaultBioToolRegistry = registryFromTools(bioAgentToolSpecs);
